version: "3.9"

services:
  jaeger:
    image: jaegertracing/all-in-one:1.55
    ports:
      - "16686:16686"   # UI
      - "14250:14250"   # OTLP gRPC
      - "14268:14268"   # Collector HTTP

  server:
    build:
      context: ..           # ← ルートをコンテキストにする
      dockerfile: Dockerfile
    working_dir: /app       # ルート (/app) を作業ディレクトリ
    command: go run ./grpc-otel-lab/cmd/server
    ports: ["50051:50051"]
    depends_on: [jaeger]
    environment:
      JAEGER_ENDPOINT: http://jaeger:14268/api/traces

  client:
    build:
      context: ..
      dockerfile: Dockerfile
    working_dir: /app
    stdin_open: true   # ← コンテナの標準入力を開いたままにする
    tty: true          # ← bash で対話可能
    entrypoint: ["/bin/bash"]
    depends_on: [server]
    environment:
      JAEGER_ENDPOINT: http://jaeger:14268/api/traces
