// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: api/chat/v1/chat.proto

package chatv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Message struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          string                 `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	Text          string                 `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	SentAtUnix    int64                  `protobuf:"varint,3,opt,name=sent_at_unix,json=sentAtUnix,proto3" json:"sent_at_unix,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_api_chat_v1_chat_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_api_chat_v1_chat_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_api_chat_v1_chat_proto_rawDescGZIP(), []int{0}
}

func (x *Message) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

func (x *Message) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *Message) GetSentAtUnix() int64 {
	if x != nil {
		return x.SentAtUnix
	}
	return 0
}

var File_api_chat_v1_chat_proto protoreflect.FileDescriptor

const file_api_chat_v1_chat_proto_rawDesc = "" +
	"\n" +
	"\x16api/chat/v1/chat.proto\x12\achat.v1\"S\n" +
	"\aMessage\x12\x12\n" +
	"\x04user\x18\x01 \x01(\tR\x04user\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\x12 \n" +
	"\fsent_at_unix\x18\x03 \x01(\x03R\n" +
	"sentAtUnix26\n" +
	"\x04Chat\x12.\n" +
	"\x04Chat\x12\x10.chat.v1.Message\x1a\x10.chat.v1.Message(\x010\x01BDZBgithub.com/izayo/go-blog-examples/grpc-otel-lab/api/chat/v1;chatv1b\x06proto3"

var (
	file_api_chat_v1_chat_proto_rawDescOnce sync.Once
	file_api_chat_v1_chat_proto_rawDescData []byte
)

func file_api_chat_v1_chat_proto_rawDescGZIP() []byte {
	file_api_chat_v1_chat_proto_rawDescOnce.Do(func() {
		file_api_chat_v1_chat_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_chat_v1_chat_proto_rawDesc), len(file_api_chat_v1_chat_proto_rawDesc)))
	})
	return file_api_chat_v1_chat_proto_rawDescData
}

var file_api_chat_v1_chat_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_api_chat_v1_chat_proto_goTypes = []any{
	(*Message)(nil), // 0: chat.v1.Message
}
var file_api_chat_v1_chat_proto_depIdxs = []int32{
	0, // 0: chat.v1.Chat.Chat:input_type -> chat.v1.Message
	0, // 1: chat.v1.Chat.Chat:output_type -> chat.v1.Message
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_chat_v1_chat_proto_init() }
func file_api_chat_v1_chat_proto_init() {
	if File_api_chat_v1_chat_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_chat_v1_chat_proto_rawDesc), len(file_api_chat_v1_chat_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_chat_v1_chat_proto_goTypes,
		DependencyIndexes: file_api_chat_v1_chat_proto_depIdxs,
		MessageInfos:      file_api_chat_v1_chat_proto_msgTypes,
	}.Build()
	File_api_chat_v1_chat_proto = out.File
	file_api_chat_v1_chat_proto_goTypes = nil
	file_api_chat_v1_chat_proto_depIdxs = nil
}
